INSERT INTO planet VALUES (41, 'cernobog-planet-1', 'An icy deserted planet that has nothing in it.');
INSERT INTO planet VALUES (42, 'cernobog-planet-2', 'This planet contains the rebel forces.');
INSERT INTO planet VALUES (43, 'cernobog-planet-3', 'This planet contains the evil forces base.');

INSERT INTO place VALUES (41, 'cernobog-planet-1-landing-zone', 'You cant see anything else than ice and its freaking cold out here. You better leave befor you freeze to death', 41);
INSERT INTO place VALUES (42, 'cernobog-planet-2-landing-zone', 'In the west is a museum, south has a market, in east is a pizza-hat and in north has a poorly fitted space ship.', 42);
INSERT INTO place VALUES (43, 'museum', 'Strange looking things are in here, your not sure could these be called art or simply junk, but you never really understood art. In the east is a landing zone.', 42);
INSERT INTO place VALUES (44, 'market', 'Here are some really strange things being sold, you cant even tell what they are. In the north is the landing zone and in east is a pharmacy.', 42);
INSERT INTO place VALUES (45, 'pizza-hat', 'It seems that where ever you go, there is going to be pizza-hat in it. you cant escape your fate of beeing pizza delivery boy to the rest of your life. In the west is a landing zone.', 42);
INSERT INTO place VALUES (46, 'pharmacy', 'Its a basic looking pharmacy, here is your everyday medicine sold as well as something that should not be sold in here. In west is a market.', 42);
INSERT INTO place VALUES (47, 'cernobog-planet-3-landing-zone', 'You see a huge gate in north which lead to a mansion, that must be where the evil forces are keeping the princess. In south is a poorly fitted space ship', 43);
INSERT INTO place VALUES (48, 'gate-to-mansion', 'A huge gate which leads to a mansion in north and in south is a landing zone.', 43);
INSERT INTO place VALUES (49, 'lounge', 'A big lounge which has entryes to east hallway and west hallway.', 43);
INSERT INTO place VALUES (410, 'east-hallway', 'Long hallway which has many doors in it, all of them seems to be locked. In the east side of hallway is a east wing and in west is lounge.', 43);
INSERT INTO place VALUES (411, 'east-wing', 'Seems to be a living quater for guards. In the west is a east hallway.', 43);
INSERT INTO place VALUES (412, 'west-hallway', 'Long hallway Which has many doors in it, all of them seems to be locked. In the west side of hallway is a west wing and in east is lounge.', 43);
INSERT INTO place VALUES (413, 'west-wing', 'Here seems to be three doors, all of them are locked. One of the doors got lable dungeon in it, perhaps the princess is kept in there. In the nort is a dungeon and in east is a west hallway.', 43);
INSERT INTO place VALUES (414, 'dungeon', 'Basic dungeon', 43);

INSERT INTO movingtable VALUES (41, 42, NULL, 41, NULL);
INSERT INTO movingtable VALUES (42, 41, NULL, 42, NULL);
INSERT INTO movingtable VALUES (43, 43, 'w', 42, NULL);
INSERT INTO movingtable VALUES (44, 44, 's', 42, NULL);
INSERT INTO movingtable VALUES (45, 45, 'e', 42, NULL);
INSERT INTO movingtable VALUES (46, 42, 'e', 43, NULL);
INSERT INTO movingtable VALUES (47, 42, 'n', 44, NULL);
INSERT INTO movingtable VALUES (48, 46, 'e', 44, NULL);
INSERT INTO movingtable VALUES (49, 42, 'w', 45, NULL);
INSERT INTO movingtable VALUES (410, 44, 'w', 46, NULL);
INSERT INTO movingtable VALUES (411, 47, NULL, 41, NULL);
INSERT INTO movingtable VALUES (412, 47, NULL, 42, NULL);
INSERT INTO movingtable VALUES (413, 41, NULL, 47, NULL);
INSERT INTO movingtable VALUES (414, 42, NULL, 47, NULL);
INSERT INTO movingtable VALUES (415, 48, 'n', 47, NULL);
INSERT INTO movingtable VALUES (416, 47, 's', 48, NULL);
INSERT INTO movingtable VALUES (417, 49, 'n', 48, NULL);
INSERT INTO movingtable VALUES (418, 48, 's', 49, NULL);
INSERT INTO movingtable VALUES (419, 410, 'e', 49, NULL);
INSERT INTO movingtable VALUES (420, 412, 'w', 49, NULL);
INSERT INTO movingtable VALUES (421, 49, 'w', 410, NULL);
INSERT INTO movingtable VALUES (422, 411, 'e', 410, NULL);
INSERT INTO movingtable VALUES (423, 410, 'w', 411, NULL);
INSERT INTO movingtable VALUES (424, 49, 'e', 412, NULL);
INSERT INTO movingtable VALUES (425, 413, 'w', 412, NULL);
INSERT INTO movingtable VALUES (426, 412, 'e', 413, NULL);
INSERT INTO movingtable VALUES (427, 414, 'n', 413, NULL);
INSERT INTO movingtable VALUES (428, 413, 's', 414, NULL);

INSERT INTO itemgroup VALUES (41, 45);
INSERT INTO itemgroup VALUES (42, 46);
INSERT INTO itemgroup VALUES (43, 49);

INSERT INTO actiontable VALUES (41, 'You go into a toilet. As you are doing you business, you see a note laying on the ground. you take the note and finnish your busines and leave.');
INSERT INTO actiontable VALUES (42, 'You combine all the pizza ingredients.');
INSERT INTO actiontable VALUES (43, 'You put the raw pizza in the oven. after a while you take the pizza out and now you have a frehly made pizza whit you.');
INSERT INTO actiontable VALUES (44, 'You combine the pizza whit lethal poison 3000.');
INSERT INTO actiontable VALUES (45, 'You press the doorbell after a while guard comes and asks you what do you want. You give him the poison pizza 3000 and you say that somebody ordered pizza to be delivered here. Guard takes the pizza, he thanks you and leaves. After that you can hear the guard yelling "Boys looks like we have some pizza to breakfast."');

INSERT INTO objecttype VALUES (41, 'door');
INSERT INTO objecttype VALUES (42, 'button');
INSERT INTO objecttype VALUES (43, 'hatch');
INSERT INTO objecttype VALUES (44, 'oven');

INSERT INTO object VALUES (41, 'toilet', 'Its a toilet, nothing more about that', 43, 1, NULL, 41);
INSERT INTO object VALUES (42, 'cold-pool', 'Its used to keep food fresh, there seems to be some tasty looking things.', 44, 1, 43, NULL);
INSERT INTO object VALUES (43, 'vegetable-shelf', 'Here seems to be all kinds of vegetables.', 44, 1, 43, NULL);
INSERT INTO object VALUES (44, 'dry-food-shelf', 'Its full of dry food ingredients.', 44, 1, 43, NULL);
INSERT INTO object VALUES (45, 'drug-shelf', 'Its full of all kinds of drugs', 46, 1, 43, NULL);
INSERT INTO object VALUES (46, 'pizza-oven', 'Its used to make delicios pizzas', 45, 1, 44, NULL);
INSERT INTO object VALUES (47, 'gate', 'Its really big gate', 48, 1, 41, NULL);
INSERT INTO object VALUES (48, 'doorbell', 'Its a white button that rings a doorbell.', 48, 41, 42, 45);
INSERT INTO object VALUES (49, 'fallen-guard', 'Seem like the pizza did its job.', 411, 41, NULL, NULL);
INSERT INTO object VALUES (410, 'dungeon-door', 'Its a door to the dungeon.', 413, 41, NULL, NULL);

INSERT INTO item VALUES (41, 'pizza-dough', 'From this pizza dough yuo can make a good pizza', 2, NULL, 44, 41, 45, 42);
INSERT INTO item VALUES (42, 'alien-mushroom', 'Looks almost like normal mushrooms, but they smell like your socks.', 1, NULL, 43, 41, 45, 42);
INSERT INTO item VALUES (43, 'alien-cheese', 'Looks like normal cheese, exept its blue.', 5, NULL, 42, 41, 45, 42);
INSERT INTO item VALUES (44, 'alien-meat', 'Its meat, thats all.', 5, NULL, 42, 41, 45, 42);
INSERT INTO item VALUES (45, 'raw-pizza', 'Looks good but its still raw.', 5, NULL, NULL, 42, 46, 43);
INSERT INTO item VALUES (46, 'pizza', 'Freshly made pizza, its smells a bit odd.', 5, NULL, NULL, 43, 49, 44);
INSERT INTO item VALUES (47, 'lethal-poison-3000', 'What ever you do whit it, dont f***ing drink it, dont even smell it, just by looking it hurts. So did you get the point? I hope so...', 3, NULL, 45, 43, 49, 44);
INSERT INTO item VALUES (48, 'hulk-potion', 'A little bottle whit hulk potion labeled in it, no idea what it means.', 4, NULL, NULL, NULL, NULL, 44);
INSERT INTO item VALUES (49, 'poison-pizza-3000', 'It looks suprisingly good and smell really good, even tough it will kill you the second your lips touch it.', 6, NULL, NULL, 42, 46, 45);
INSERT INTO item VALUES (410, 'dungeon-key-card', 'A key card to the dungeon where the princess is probably kept.', 1, NULL, 49, NULL, NULL, NULL);
